
# 24.9. Debugging calls to requests.get()

[toc]

## 24.9.1. In the Runestone environment

In our limited implementation of the requests library for the Runestone environment, if your request fails for any reason, you will still get a <font color=red> Response object </font>.
- invoke the `.json()` method on the <font color=red> Response object </font> and you get an error that refers to an “unexpected token” in the JSON.

**When that happens, print out the values of the `.text` and `.url` attributes**.

1. *unable to use your baseurl and params value* to create a url string. **wrong URL**
    - the `.url` attribute will be <font color=dpurple> "Couldn’t generate a valid URL” </font>
    - the `.text` attribute will be set to “`<html><body><h1>invalid request</h1></body></html>`”.

In that case, check the value for the params parameter is indeed a dictionary and that its keys and values are all strings.

2. Igenerated a url string but *failed to fetch data from the server described by the url string*.
- the `.url` attribute will be set correctly
- the `.text` attribute will be set to <font color=dpurple> “Failed to retrieve that URL” </font> or `[]`.

In that case, examine the url to try to figure out what went wrong. print it, then copy and paste it to a browser window and see what happens.

the results you are getting back from a call to requests.get() are not what you expected
- look at the first few characters of the .text attribute of the Response object

a `runtime error` and you don’t get a Response object back from the call to requests.get()
- invoke the requestURL() function with the same parameters you used to invoke requests.get()

a runtime error and you don’t get a Response object back from the call to requests.get()
- look at the values you passed in to requests.get()

---

## 24.9.2. In a full python environment

In a full python environment, will not always get a Response object back from a call to requests.get.

get back will generally be even more informative than what you get in the Runestone environment.

1. get a <fonr color=red> runtime error </font> when you call `requests.get(dest_url)`.
    - **two possibilities**

    - the value provided for the params parameter is not a valid dictionary or doesn’t have key-value pairs that can be converted into text strings suitable for putting into a URL.
      - For example, if you execute `requests.get("http://github.com", params = [0,1])`, [0,1] is a list rather than a dictionary and the python interpreter generates the error, <font color=dpurple>  TypeError: 'int' object is not iterable </font>.

    - the variable dest_url is either not bound to a string, or is bound to a string that isn’t a valid URL.
      - For example, it might be bound to the string "http://foo.bar/bat". foo.bar is not a valid domain name that can be resolved to an ip address, so there’s no server to contact. That will yield an error of <font color=dpurple>  type requests.exceptions.ConnectionError </font>.
      - complete error message: requests.exceptions.ConnectionError: HTTPConnectionPool(host='foo.bar', port=80): Max retries exceeded with url: /bat?key=val (Caused by <class 'socket.gaierror'>: [Errno 11004] getaddrinfo failed)


The best approach is to look at the URL that is produced, eyeball it, and plug it into a browser to see what happens.

if the call to `requests.get` produces an error, you won’t get a Response object, need some other way to see what URL was produced.

The function defined below takes the same parameters as `requests.get` and returns the URL as a string, without trying to fetch it.

```py
import requests

def requestURL(baseurl, params = {}):
    # accepts a URL path and a params diction as inputs.
    # calls requests.get() with those inputs,
    # and returns the full URL of the data you want to get.
    req = requests.Request(method = 'GET', url = baseurl, params = params)
    prepped = req.prepare()
    return prepped.url

print(requestURL(some_base_url, some_params_dictionary))

https://api.datamuse.com/words?rel_rhy=funny

print(requestURL("https://api.datamuse.com/words", {"rel_rhy":"funny"}) )

```

If requests.get() executes without generating a runtime error, you are still not done with your error checking. No error means that your computer managed to connect to some web server and get some kind of response, but it doesn’t mean that it got the data you were hoping to get.

Fortunately, the response object returned by requests.get() has the .url attribute, which will help you with debugging. It’s a good practice during program development to have your program print it out. This is easier than calling requestURL() but is only available to you if requests.get() succeeds in returning a Response object.































.
